spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meta_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true      # SQL 쿼리 로깅 (개발 중에만 true)
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/meta_db?authSource=admin
      database: meta_db
      auto-index-creation: true
  kafka:
    bootstrap-servers: localhost:9092
  ai:
    openai:
      api-key: ${GPT_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
    gemini:
      api-key: ${GEMINI_API_KEY}
      base-url: "https://generativelanguage.googleapis.com/v1beta/openai/"
      chat:
        options:
          model: gemini-2.5-flash
#  flyway:
#    enabled: true   # 처음 실행할 때는 false, 이후에 true로 변경(flyway 인덱스 생성)
#    baseline-on-migrate: true   # 그냥 놔둬도됨
#    baseline-version: 0   # V0 스킵, V1부터 마이그레이션

app:
  cookie:
    secure: false
    domain: ""

fcm:
  firebase-adminsdk: file:./firebase-adminsdk.json

logging:
  level:
    org.springframework.web: DEBUG
    com.loopin: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

springdoc:
  server-url: http://localhost:8080

resilience4j:
  circuitbreaker:
    instances:
      open-ai:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 5s
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 2
      gemini:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 5s
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 2
